### ISSUE TITLE
Configuration issue - cannot authenticate

### ISSUE THREAD

**Issue by garethcook** [snicker/zwift_hass#35]
I'm not having much success with the logs reporting an authentication error. I've tried changing my password, and my ID in the .fit URL and in the local PC directory match, so I know that's my username

I'm seeing post in different place with different configs. The official one is :

```
sensor:
  - platform: zwift
    username: !secret my6digitIDhere
    password: !secret mypasswordhere
```

Which fails as HA refuses to start with:
`The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: Secret my6digitIDhere not defined`

If I have the same config with the '!secret' removed which I've seen in the linked discussion, I can restart but the authentication error occurs
```
sensor:
  - platform: zwift
    username: my6digitIDhere
    password: mypasswordhere
```

I'm a little stuck, the documentation doesn't appear to match what we're expecting
